version: '3'

services:
    echoer:
        build: .
        environment:
            - BROKER_HOSTNAME=rabbitmq
            - DB_HOSTNAME=postgres
            - DB_PASSWORD=password
        depends_on:
            - rabbitmq
            - postgres

    rabbitmq:
        image: "rabbitmq"

    postgres:
        image: "postgres"
        environment:
            - POSTGRES_PASSWORD=password